name: report

on:
  schedule:
    # - cron: "0 10 * * *" #  Brasília - DF está 2 horas à frente de Washington, D.C., Distrito de Columbia, EUA
    # - cron: "0,5,10,15 * * * *" #  Brasília - DF está 2 horas à frente de Washington, D.C., Distrito de Columbia, EUA
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID_TO_NOTIFY: ${{ secrets.TELEGRAM_CHAT_ID_TO_NOTIFY }}
      TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm start
